### PR TITLE
removed printer related functions to make the source compile

### PR DESCRIPTION
**Pull request by dxhisboy**
It reports `undefined reference to 'printer_write'` and some other functions.
I noticed that some textprint.c is filtered out from Makefile. So I think you are currently disabling such functionality. So I have some ugly hacks that removed printer related functions and make the source able to compile.
Also added something to .gitignore so that we can ignore bin dir.

### CODE REVIEW

**Comment by paolo-sz** [comment]
Thanks for your effort.
As far I remember my last commit was compiling fine...
In any case I can tell you I was not going to remove printing features, if anything happens in that sense, it is because of mintty merge...
Unfortunately my PC burnt-out so I cannot really look into this stuff until mid/end of September.
I will let you know asap...

**Comment by dxhisboy** [comment]
Maybe of my Cygwin version?
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/7.4.0/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-7.4.0-1.x86_64/src/gcc-7.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
gcc version 7.4.0 (GCC)
```

**Comment by paolo-sz** [comment]
Sorry for the very late reply... my pc troubles are too long... :-(

Anyway, are you still experiencing issues or you got the clue?
Just a check, do you have, in src folder, a link winprint.c pointing to ../attic/winprint.c ?
That link was indeed not versioned (I just added it with my latest push)...

**Comment by mskyaxl** [comment]
@paolo-sz can you please update the build steps in the readme of your master? I get segmentation fault if I build with the latest cygwin. THanks!

**Comment by paolo-sz** [comment]
@mskyaxl, the readme is basically still valid for compiling the code... and I got no issue while compiling it.
As you can see from the above, I did some very bad things (force-push) to the repo... have you tried to clone out a complete fresh version?
If this still no helps could you provide me the full compile log? Maybe I can get some clue...

**Comment by mskyaxl** [comment]
the compilation of your master is successful but when I run fatty I get segmentation fault whith this:
dump

[fatty.exe.stackdump.txt](https://github.com/paolo-sz/fatty/files/4514825/fatty.exe.stackdump.txt)

My installed cygwin packages are:
[installed.txt](https://github.com/paolo-sz/fatty/files/4514819/installed.txt)

**Comment by paolo-sz** [comment]
Mmmm... try to temove the <code>-fstack-check</code> from the <code>$(BINDIR)/term.o:</code> target in src/Makefile
That option was originally not present on the compile line... I added it back just as a try and it worked for me...
Even if that fixes your issue, it is far from being the correct fix...

**Comment by paolo-sz** [comment]
> My installed cygwin packages are:
> [installed.txt](https://github.com/paolo-sz/fatty/files/4514819/installed.txt)

a lot of differences from my installed packages... one very interesting is that I have an older gcc (9.3.0-1)

**Comment by paolo-sz** [comment]
Just updated cygwin... still no issue on my side...
Try a complete new build with <code>make DEBUG=1</code>
Then run fatty under gdb and look at the backtrace when it crashes...

BTW these are my installed packages 
[installed_my.txt](https://github.com/paolo-sz/fatty/files/4514988/installed_my.txt)

**Comment by paolo-sz** [comment]
@mskyaxl maybe should better to move our discussion on another thread... please let continue on #2

**Comment by paolo-sz** [comment]
No need to remove functions, commit 69209b1e1d2879d4530d7d420ddf9c082c3ff58f should fix the compiling issue.
Closing the pull request.

**Pull request closed without merging**
